name: 健康上报
on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 0表示北京时间早上8点
    - cron: "0 18 * * *"
  push:
    branches:
      - master
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 使用 node:14
      - name: 使用 Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
          dotnet tool run Web.Ping --host https://app.cqksy.cn
#          QQ='${{ secrets.QQ }}' EMAIL='${{ secrets.EMAIL }}' CQZK='${{ secrets.CQZK }}' REPORTADD='${{ secrets.REPORTADD }}' npm run report
        env:
          CI: true
